/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rene' at '11/9/16 12:08 PM' with Gradle 3.1
 *
 * @author Rene, @date 11/9/16 12:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
